Add XML tag context to attribute error messages
When a required XML attribute is missing, the error message now includes
the name of the parent XML tag to help users quickly identify where the
missing attribute is expected.

Before:
  ERROR: Attribute "from" is required, but was not defined.

After:
  ERROR: Tag <receive-mesh>: Attribute "from" is required, but was not defined.

Similarly, the invalid-value error now also includes the tag name for
consistency:

Before:
  ERROR: Invalid value "..." of attribute "...": ...

After:
  ERROR: Tag <...>: Invalid value "..." of attribute "...": ...

Closes #2441