Replace Ginkgo kernel launch by Kokkos extension (#2051)
* remove deprecated ginkgo parts

* move definitions into separate file

* Small cosmetics

* make compile with kokkos layer

* fixes cmake

* add second kernel

* kernel fixup

* fix kernels

* maybe fix host/device functions

* fixes transposed access to device arrays

* initializes kokkos for ginkgo

* COnvergence checks updates

* Handle initialization of Kokkos appropriately

* Handle finalization properly

* Port to kokkos-mapping branch of Ginkgo develop

---------

Co-authored-by: Marcel Koch <marcel.koch@kit.edu>

* Fix invokaction/signature of device solver functions

* Inline lambdas to make the CUDA compiler happy
Preventing error messages of the form:
error: An extended __host__ __device__ lambda cannot be defined inside a generic lambda expression("operator()").

* Make compile with Cuda

* Use correct permutation for CUDA

* Use Serial Kokkos for Ginkgo Reference executor

* Compile helper library as a static library

* Rename OpenMP Kokkos macro to correct name

* Some CMake compatibility updates

* Use correct hipsolver path

* Update deprecated lend Ginkgo function

* Replace __device__ constant by PP definition

* Forward compile definitions to preCICE as well

* Use pointer-based array access to bypass bound-checking in debug mode

* Use Kokkos log and fma

* Indentation using clang-format

* Move Ginkgo utils to device directory

* Move initializer to device namespace

* Move Ginkgo tests to Fedora images

* Add changelog entry

* Clean-up CMake documentation

* Rename PRECICE_WITH_OMP to PRECICE_WITH_OPENMP

* Fix typo

* Prepend PP variable with PRECICE and undefine afterwards

* Prepend PRECICE_ for LOG and FMA macros, and undefine afterwards

* compile preciceCore with EIGEN_NO_CUDA

* Consistent initialization of Ginkgo and check for finalization

* Make ::min clash compile with device compiler wrappers

* Compile everything into preciceCore

* Set visibility flag conditionally

* Use explicit if's for visibility

* Final clean-up

---------

Co-authored-by: Marcel Koch <marcel.koch@kit.edu>
Co-authored-by: David Schneider <schneidd@ipvs.uni-stuttgart.de>